version: "3.9"

services:
  # TODO: Add production build for BE && FE
  api:
    build:
      context: api
      args:
        HOST_USER_NAME: ${HOST_USER_NAME} # from .env file
    env_file: .env
    ports:
      - "443:8080"
    depends_on:
      - redisGrap
    links:
      - redisGraph

  # TODO:
  #   - Add password to the database
  #   - Try removing the port and connecting from inside of the api container
  redisGraph:
    image: "redislabs/redisgraph:2.8.13"
    ports:
      - "6379:6379"
    volumes:
      - "./db-data/redisGraph:/data"
